title: Streamdata Gallery AWS Internet of Things
url: aws-internet-of-things.streamdata.gallery
tag: AWS Internet of Things
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: aws-internet-of-things
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
